### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by JostMigenda** [icecube/FIRESONG#55]
_[As part of the [JOSS review](https://github.com/openjournals/joss-reviews/issues/3194).]_

I ran into several issues while trying to install FIRESONG.
- [x] The installation instructions in the README file are currently incomplete: If you recommend installing FIRESONG as an editable install from a local folder (`pip install --editable FIRESONG`), you need to state explicitly that the user should download the repo first.
However, note that edible installs are mainly for developers of a package. For users, publishing FIRESONG to PyPI and installing via `pip install FIRESONG` (i.e. without downloading the repo) may be preferable; both for simplicity and to ensure they install a tagged release (as opposed to the most recent git commit on the base branch, which is more prone to cause confusion).
- [x] Right now, installing FIRESONG does not install any dependencies; so after installing it into an empty conda environment, I get an error message ("ModuleNotFoundError: No module named 'numpy'") when trying to run e.g. `from firesong.Firesong import firesong_simulation`. You can use setup.py’s [`install_requires` keyword](https://packaging.python.org/guides/distributing-packages-using-setuptools/#install-requires) to let pip install these dependencies automatically.
- [x] Since FIRESONG documentation is mainly in the form of Jupyter notebooks, it would be useful to add jupyter and matplotlib as dependencies.

**Comment by JostMigenda** [comment]
Additionally, one of the dependencies (CosmoloPy) apparently fails to install under Python 3.8 or newer. I’ve [opened an issue](https://github.com/roban/CosmoloPy/issues/9) on the CosmoloPy repo.
Please let me know whether there’s a workaround or whether I should continue testing with Python 3.7 for now.

**Comment by JostMigenda** [comment]
[This commit](https://github.com/icecube/FIRESONG/commit/f331935d34dee2ad423b9d95050d07079bf867a2) solves the issues listed above, thank you! And in the meantime, the CosmoloPy issue was also fixed and it can now be pip-installed under Python 3.8 as well, so I will continue to use that for testing.

3.9 isn’t supported by CosmoloPy yet, though; it would probably be good to mention that in the README file to save users some trouble trying to debug it.
Also, the version you uploaded to PyPI is still missing the jupyter and matplotlib requirements, unfortunately; it looks like you uploaded an incomplete version of the code there?

PS: If you weren’t already aware of it, check out [this GitHub Action](https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries) to automate publishing to PyPI whenever you create a new release; maybe that’s helpful to you?

**Comment by ChrisCFTung** [comment]
Hi @JostMigenda,

Sorry about the confusion, that previous version I uploaded to pypi was not ready. In order to address the issues you mentioned, I have released a new version v.1.6.1 (also updated on PyPI), which no longer require cosmolopy. I believe this can avoid any future python version issue. The switch has effectively no impact on the result.

regarding the requirement of `jupyter` and `matplotlib`, I think they are not really involved in the core functions of FIRESONG, so I don't want to force users to install these packages. However, I have stated explicitly in the README that access to the examples requires jupyter notebook and matplotlib. Please let me know if that make sense to you.

And thank you for the suggestion on publishing automatically to PyPI. I will definitely implement that.

**Comment by JostMigenda** [comment]
Nice to see that removing the dependency on cosmolopy was possible without too much trouble; this should indeed prevent most issues with future Python versions. Regarding `jupyter` and `matplotlib`, that seems like a good compromise to me, yes. Thanks!
